=== egortrue/rustberries/L0/data/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "order_uid": {
            "type": "string"
        },
        "track_number": {
            "type": "string"
        },
        "entry": {
            "type": "string"
        },
        "delivery": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            },
            "required": [
                "name",
                "phone",
                "zip",
                "city",
                "address",
                "region",
                "email"
            ]
        },
        "payment": {
            "type": "object",
            "properties": {
                "transaction": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer",
                    "minimum": 0
                },
                "payment_dt": {
                    "type": "integer",
                    "minimum": 0
                },
                "bank": {
                    "type": "string"
                },
                "delivery_cost": {
                    "type": "integer",
                    "minimum": 0
                },
                "goods_total": {
                    "type": "integer",
                    "minimum": 0
                },
                "custom_fee": {
                    "type": "integer",
                    "minimum": 0
                }
            },
            "required": [
                "transaction",
                "request_id",
                "currency",
                "provider",
                "amount",
                "payment_dt",
                "bank",
                "delivery_cost",
                "goods_total",
                "custom_fee"
            ]
        },
        "items": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "chrt_id": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "track_number": {
                            "type": "string"
                        },
                        "price": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "rid": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "sale": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "size": {
                            "type": "string"
                        },
                        "total_price": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "nm_id": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "brand": {
                            "type": "string"
                        },
                        "status": {
                            "type": "integer",
                            "minimum": 0
                        }
                    },
                    "required": [
                        "chrt_id",
                        "track_number",
                        "price",
                        "rid",
                        "name",
                        "sale",
                        "size",
                        "total_price",
                        "nm_id",
                        "brand",
                        "status"
                    ]
                }
            ]
        },
        "locale": {
            "type": "string"
        },
        "internal_signature": {
            "type": "string"
        },
        "customer_id": {
            "type": "string"
        },
        "delivery_service": {
            "type": "string"
        },
        "shardkey": {
            "type": "string"
        },
        "sm_id": {
            "type": "integer",
            "minimum": 0
        },
        "date_created": {
            "type": "string"
        },
        "oof_shard": {
            "type": "string"
        }
    },
    "required": [
        "order_uid",
        "track_number",
        "entry",
        "delivery",
        "payment",
        "items",
        "locale",
        "internal_signature",
        "customer_id",
        "delivery_service",
        "shardkey",
        "sm_id",
        "date_created",
        "oof_shard"
    ]
}

=== egortrue/rustberries/L0/data/generated.json
[
    {
        "order_uid": "eu veniam",
        "track_number": "aliquip tempor culpa Ut Lorem",
        "entry": "commodo incididunt et elit quis",
        "delivery": {
            "name": "incididunt officia",
            "phone": "eiusmod",
            "zip": "officia aute Ut",
            "city": "dolor laborum elit ut",
            "address": "in ex",
            "region": "magna ad eu ullamco aliquip",
            "email": "do sit enim irure"
        },
        "payment": {
            "transaction": "sint eiusmod aliquip eu",
            "request_id": "nisi dolore dolore",
            "currency": "id",
            "provider": "ea in do",
            "amount": 29199059,
            "payment_dt": 7664168,
            "bank": "est",
            "delivery_cost": 48679645,
            "goods_total": 30207324,
            "custom_fee": 79619288
        },
        "items": [
            {
                "chrt_id": 89336426,
                "track_number": "ipsum sed dolore aute",
                "price": 27211763,
                "rid": "culpa",
                "name": "aute",
                "sale": 33416743,
                "size": "consequat in minim",
                "total_price": 60432134,
                "nm_id": 93627512,
                "brand": "in dolor officia Lorem reprehenderit",
                "status": 84135348
            }
        ],
        "locale": "fugiat tempor ea deserunt",
        "internal_signature": "dolor",
        "customer_id": "deserunt ex",
        "delivery_service": "qui",
        "shardkey": "officia do sint veniam dolore",
        "sm_id": 25265151,
        "date_created": "sint in",
        "oof_shard": "eiusmod quis irure cillum nulla"
    },
    {
        "order_uid": "id qui sint labore dolor",
        "track_number": "Duis laborum occaecat",
        "entry": "culpa deserunt",
        "delivery": {
            "name": "ut exercitation culpa",
            "phone": "nostrud adipisicing dolore",
            "zip": "occaecat nostrud sint ad",
            "city": "voluptate",
            "address": "dolor",
            "region": "reprehenderit Ut exercitation",
            "email": "cillum eu voluptate"
        },
        "payment": {
            "transaction": "exercitation anim sed dolore",
            "request_id": "consectetur magna ad Lorem",
            "currency": "sunt dolore",
            "provider": "tempor nulla",
            "amount": 48375773,
            "payment_dt": 76912864,
            "bank": "veniam in",
            "delivery_cost": 32481279,
            "goods_total": 77921457,
            "custom_fee": 21940013
        },
        "items": [
            {
                "chrt_id": 45712957,
                "track_number": "Excepteur aliquip sunt",
                "price": 77849251,
                "rid": "amet",
                "name": "labore Lorem officia exercitation et",
                "sale": 81005678,
                "size": "aute consequat culpa",
                "total_price": 93549461,
                "nm_id": 92005551,
                "brand": "occaecat proident incididunt",
                "status": 47326462
            }
        ],
        "locale": "fugiat consequat voluptate deserunt sed",
        "internal_signature": "ipsum Excepteur commodo in esse",
        "customer_id": "ipsum consectetur",
        "delivery_service": "non ad ipsum tempor laborum",
        "shardkey": "sint ipsum",
        "sm_id": 22399463,
        "date_created": "sed consectetur eu eiusmod ad",
        "oof_shard": "nostrud do ad"
    },
    {
        "order_uid": "Excepteur",
        "track_number": "proident",
        "entry": "Lorem reprehenderit dolore",
        "delivery": {
            "name": "irure Ut enim ea",
            "phone": "elit ullamco",
            "zip": "officia dolor Duis labore pariatur",
            "city": "aliquip",
            "address": "elit officia in dolor",
            "region": "et ipsum",
            "email": "laborum qui voluptate aliqua"
        },
        "payment": {
            "transaction": "nisi enim et dolor",
            "request_id": "id irure sunt",
            "currency": "aliquip fugiat",
            "provider": "cillum Duis",
            "amount": 82611157,
            "payment_dt": 47445999,
            "bank": "mollit et adipisicing ut",
            "delivery_cost": 84599730,
            "goods_total": 46672545,
            "custom_fee": 69206371
        },
        "items": [
            {
                "chrt_id": 22234814,
                "track_number": "consequat",
                "price": 45203887,
                "rid": "in pariatur non in",
                "name": "adipisicing elit quis magna",
                "sale": 4732291,
                "size": "ut veniam fugiat incididunt voluptate",
                "total_price": 91273380,
                "nm_id": 52147063,
                "brand": "laboris commodo",
                "status": 6901837
            }
        ],
        "locale": "occaecat dolore ipsum velit sit",
        "internal_signature": "dolor",
        "customer_id": "laborum occaecat consectetur in",
        "delivery_service": "cillum laborum",
        "shardkey": "enim mollit consectetur aute",
        "sm_id": 66061103,
        "date_created": "incididunt nulla non laboris voluptate",
        "oof_shard": "dolor"
    },
    {
        "order_uid": "sed Lorem",
        "track_number": "et deserunt",
        "entry": "mollit dolore voluptate cupidatat aute",
        "delivery": {
            "name": "culpa voluptate veniam tempor",
            "phone": "dolore esse ipsum",
            "zip": "fugiat anim proident pariatur non",
            "city": "id labore",
            "address": "sint elit sunt ex amet",
            "region": "eu sunt eiusmod",
            "email": "fugiat Lorem aute"
        },
        "payment": {
            "transaction": "Excepteur",
            "request_id": "Excepteur veniam sint",
            "currency": "do",
            "provider": "nostrud",
            "amount": 37022081,
            "payment_dt": 88777099,
            "bank": "deserunt Excepteur adipisicing qui",
            "delivery_cost": 26933677,
            "goods_total": 31111587,
            "custom_fee": 86103164
        },
        "items": [
            {
                "chrt_id": 55394873,
                "track_number": "aliquip fugiat dolor",
                "price": 66165107,
                "rid": "ut veniam ad elit ullamco",
                "name": "eiusmod ut ad",
                "sale": 28394368,
                "size": "id ullamco",
                "total_price": 48512885,
                "nm_id": 93278494,
                "brand": "ea aliquip quis ullamco labore",
                "status": 78486537
            }
        ],
        "locale": "aliqua Lorem cillum",
        "internal_signature": "dolor",
        "customer_id": "voluptate in commodo veniam pariatur",
        "delivery_service": "Ut sed fugiat",
        "shardkey": "cillum sint",
        "sm_id": 33474926,
        "date_created": "deserunt",
        "oof_shard": "dolor laborum incididunt"
    },
    {
        "order_uid": "nulla dolor officia amet eu",
        "track_number": "ullamco sint culpa Duis",
        "entry": "est in",
        "delivery": {
            "name": "ullamco velit dolor",
            "phone": "magna voluptate culpa",
            "zip": "ut occaecat proident aliqua",
            "city": "nostrud sint eiusmod",
            "address": "et fugiat laborum culpa",
            "region": "dolore",
            "email": "esse elit in"
        },
        "payment": {
            "transaction": "dolore id",
            "request_id": "minim exercitation est dolore",
            "currency": "tempor irure aliqua",
            "provider": "ipsum",
            "amount": 55695248,
            "payment_dt": 10694916,
            "bank": "consectetur irure officia aute culpa",
            "delivery_cost": 80863714,
            "goods_total": 17927344,
            "custom_fee": 66475717
        },
        "items": [
            {
                "chrt_id": 92190304,
                "track_number": "est minim",
                "price": 42580198,
                "rid": "ut do",
                "name": "nisi Ut eiusmod adipisicing in",
                "sale": 84461027,
                "size": "irure anim officia",
                "total_price": 5071833,
                "nm_id": 84385696,
                "brand": "est in nulla non",
                "status": 92525279
            }
        ],
        "locale": "Ut voluptate in nulla veniam",
        "internal_signature": "ipsum proident sint",
        "customer_id": "amet",
        "delivery_service": "aliquip Duis cupidatat incididunt",
        "shardkey": "in dolore",
        "sm_id": 17250691,
        "date_created": "enim officia Lorem quis",
        "oof_shard": "elit do dolore"
    },
    {
        "order_uid": "consectetur Duis ipsum reprehenderit dolore",
        "track_number": "ex ullamco",
        "entry": "labore eu quis id",
        "delivery": {
            "name": "laborum occaecat",
            "phone": "ut magna quis incididunt in",
            "zip": "dolore commodo amet non",
            "city": "ea pariatur ut",
            "address": "esse ea dolore fugiat",
            "region": "aliquip dolore",
            "email": "anim dolore commodo non minim"
        },
        "payment": {
            "transaction": "dolore Duis aliqua nostrud reprehenderit",
            "request_id": "minim",
            "currency": "ex irure",
            "provider": "eu",
            "amount": 7260853,
            "payment_dt": 16626746,
            "bank": "eiusmod",
            "delivery_cost": 85982055,
            "goods_total": 88825705,
            "custom_fee": 57849558
        },
        "items": [
            {
                "chrt_id": 84248567,
                "track_number": "ea nulla minim",
                "price": 56705933,
